name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: [1, 2, 3, 4, 5]
    steps:
      - run: echo "${{ matrix.v }}"
